cmake_minimum_required(VERSION 3.6)
PROJECT(quartz)
if(CMAKE_BUILD_TYPE MATCHES "Debug")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG $ENV{CPP_WORKSPACE}/bin/Debug)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG $ENV{CPP_WORKSPACE}/bin/Debug)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE $ENV{CPP_WORKSPACE}/bin/Debug)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE $ENV{CPP_WORKSPACE}/bin/Debug)
else()
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG $ENV{CPP_WORKSPACE}/bin/Release)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG $ENV{CPP_WORKSPACE}/bin/Release)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE $ENV{CPP_WORKSPACE}/bin/Release)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE $ENV{CPP_WORKSPACE}/bin/Release)
endif()

add_compile_options(-std=c++11 -Wall)

set(CMAKE_SKIP_BUILD_RPATH FALSE)
set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
set(CMAKE_INSTALL_RPATH ".")
#set(CMAKE_INSTALL_RPATH_USE_LINK_PATH FALSE)

set(CMAKE_C_FLAGS_Release "${CMAKE_C_FLAGS_Release} -O3")

add_subdirectory(src)
#add_subdirectory(test)

